# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-13 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20200413_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default='', max_length=700),
        ),
    ]
