# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-20 18:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20200420_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='user',
        ),
    ]
