# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-20 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_remove_userorder_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100),
        ),
    ]
