# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-20 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_userorder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
