# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-20 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0012_remove_userorder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='total_price',
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.UserOrder'),
        ),
    ]
