# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-20 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_auto_20200420_2107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserOrder',
            new_name='Order',
        ),
    ]
